.\" (C) Copyright 2015 Kyle Moffett <kyle@moffetthome.net>,
.\"
.TH BAZEL 1 "2015-04-15" Linux
.SH NAME
bazel \- {Fast, Correct} - Choose two
.SH SYNOPSIS
.B bazel
.RI "<startup-options> <command> <options>"
.br
.B bazel
.RI "build <options> //my/build:target ..."
.br
.SH DESCRIPTION
Bazel is a build tool that builds code quickly and reliably. It is used to build
the majority of Google's software, and thus it has been designed to handle
build problems present in Google's development environment.
.PP
For now, the documentation of
.B bazel
can be accessed by running
.B bazel help
.SH TODO
TODO(kmoffett): Fill in this manpage
